### ISSUE TITLE
Mirjam struggles with Task 1

### ISSUE THREAD

**Issue by SirSprinkles** [KadinTucker/Basket-Ball#2]
Hello.
I am trying to implement the explicit euler method. It is supposed to solve a differential equation. I am currently testing with y'=y+x.
That however produces an error instead of a result. 
I am not sure why. Please help. 
I have a feeling i am missing something obvious. But it might be theory.

Also i cant seem to add a file here... Kadin?
For now it is task 1 from me. the error comes up for the definition of u0. Thank you

**Comment by SirSprinkles** [comment]
I am also not sure why the task wants me to return both arrays of ti and ui. since ti is just what i am iterating through.

**Comment by SirSprinkles** [comment]
nvm.

**Comment by KadinTucker** [comment]
Hello,
Look at the document `using-git.md`--it gives a more comprehensive explanation of how one can add and update their files. 
I would suggest adding documentation to your code and more clearly explaining which variables mean what, that will make it much easier to read it and find any errors therein. At the moment I don't really understand what you are trying to do with your code.
